services:
  db:
    image: postgres:latest
    container_name: postgres-todolist
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password  # 원하는 비밀번호로 변경
      POSTGRES_DB: todolist
    volumes:
      - db_data:/var/lib/postgresql/data

  spring-app:
    image: .
    container_name: spring-app
    environment:
      - SPRING_DATASOURCE_URL = jdbc:postgresql://db:5432/todolist


  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "6666:6666"
    volumes:
      # 1. 호스트에 준비한 Nginx 설정 파일 마운트
      # 왼쪽 경로는 호스트의 파일 경로입니다. 실제 파일 위치에 맞게 수정하세요.
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf:ro

      # 2. Certbot 인증서 디렉토리 마운트 (읽기 전용)
      # 호스트의 /etc/letsencrypt 전체를 컨테이너의 /etc/letsencrypt로 마운트
      - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  db_data: