spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todolist
    username: postgres
    password: test-password-for-local
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

jwt:
  secret: your_jwt_secret_key_your_jwt_secret_keyyour_jwt_secret_key_your_jwt_secret_keyyour_jwt_secret_key_your_jwt_secret_key
  expiration: 36000